### PR TITLE
Allow join of two collection

### PR DESCRIPTION
**Pull request by cipous**
There are two commits, the latter is just because tests are not working on windows and this commit can be removed.

I dont know whether target should be 1.5.x or master, so please correct me.

### CODE REVIEW

**Comment by christophstrobl** [comment]
thanks @cipous and sorry for long silence. have you signed the CLA? if not please do so and add your confirmation number to this PR so I can take it from there.

**Comment by cipous** [comment]
My CLA: 140220150929023831

**Comment by christophstrobl** [comment]
@cipous that was fast :open_mouth:

**Comment by christophstrobl** [comment]
thanks @cipous . merged via bd610f1.

**Pull request closed without merging**
