### PR TITLE
DATASOLR-215:added request method to accommodate HTTP POST on queryForP…

### PR DESCRIPTION
**Pull request by satya5574**
…age API

Change-Id: I41cf02c6b6aef989a7a3b2743301c849b8f0c662

1>Added RequestMethod enum for HTTP method types
2>Overridden queryForPage method in SolrTemplate to accommodate HTTP POST

### CODE REVIEW

**Comment by christophstrobl** [comment]
thanks @satya5574! Could you please sign the [contributor's agreement](https://support.springsource.com/spring_committer_signup) and add your CLA No. as a comment to [DATASOLR-215](https://jira.spring.io/browse/DATASOLR-215) so I can go on an take things from here.

**Comment by satya5574** [comment]
Hello sateesh shiradwade

Thank you but our records indicate that you have already accepted the individual contributor agreement. If you are interested in participating in an additional Spring project, please contact the appropriate project lead and indicate that you have already signed the Spring Contributor Agreement. Once signed agreement covers participating in as many Spring projects as you need.

Your confirmation number is: 123720150529034323

**Comment by satya5574** [comment]
My apologies, Not sure the above confirmation no si the one your asking or the one below ..
 ICLA 101414

**Comment by satya5574** [comment]
@christophstrobl  hi, this is my first contribution ... I am not sure about the process . Will you please let me know if its waiting for some more review or something from my side need to be done ..  And also will i get any intimation when it get merged to master ??

**Comment by cipous** [comment]
He probably means https://support.springsource.com/spring_committer_signup .

**Comment by satya5574** [comment]
I have already done that ...  When i try again , i get confirmation message saying "i have already signed the agreement"
Hello shiradwade sateesh krishna
Thank you but our records indicate that you have already accepted the individual contributor agreement. If you are interested in participating in an additional Spring project, please contact the appropriate project lead and indicate that you have already signed the Spring Contributor Agreement. Once signed agreement covers participating in as many Spring projects as you need.Your confirmation number is: 123720150529034323
BrSateesh      From: cipous <notifications@github.com>
 To: spring-projects/spring-data-solr <spring-data-solr@noreply.github.com> 
Cc: satya5574 <sateesh_ks@yahoo.com> 
 Sent: Tuesday, September 29, 2015 11:14 AM
 Subject: Re: [spring-data-solr] DATASOLR-215:added request method to accommodate HTTP POST on queryForP… (#52)
   
He probably means https://support.springsource.com/spring_committer_signup .—

**Comment by cipous** [comment]
now you have conflicts, so you have to merge changes from target to your source

**Comment by satya5574** [comment]
@cipous 
i pulled latest from target (spring-projects:master) and don't see any issues or conflict . . Where do u see the conflicts ??..

**Comment by satya5574** [comment]
ohh my bad its on my fork .. to data solr-215 .. got it

**Comment by satya5574** [comment]
@christophstrobl  @cipous  Hi, Now i had resolved conflicts on my fork and created a branch on my fork "issues/DATASOLR-215" , how do i duplicate this branch on main repo and create a PR again going against main master . OR is there a direct way i can modify my PR to point to original master from my forked repo issue branch ?? Please advise. 
Br
Sateesh

**Comment by SenthilKumaravel** [comment]
Hi Ya, 
Shall I use spring data Solr with Solr 5.2.1 version? I was unable to use CloudSolrClient. 
Cheers,
Senthil.

**Comment by christophstrobl** [comment]
thanks patience and sorry for the delay @satya5574 . Changes have been merged via 06360038ed66a4bb6d675f4ac95021ca3b9cf5ff.

**Pull request closed without merging**
