### PR TITLE
DATASOLR-86: Added support for range facets

### PR DESCRIPTION
**Pull request by juhrlass**
Added FacetRangeOptions similar to FacetOptions that allows the creation of range facets.
Extended DefaultQueryParser and ResultHelper to support range facets in queries and results.

See: https://jira.springsource.org/browse/DATASOLR-86

### CODE REVIEW

**Comment by paranoiabla** [comment]
+ 1 on this :)

**Comment by michaelgriffithus** [comment]
When is this RangeFacet feature going to make it into the spring data solr code base?

**Comment by apoorvmittal10** [comment]
Any plans to merge it? Is there any other option to get facet range data using spring-data for the time the request not gets merged?

**Comment by Rene-Dieckmann** [comment]
+1 for merge

**Comment by apoorvmittal10** [comment]
+1 for merge

**Pull request closed without merging**
